name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lhvy/metrics@9d8432e60ecf86705b6792457ac7b3e29ff76306
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: yttam
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Australia/Sydney
          plugin_music: yes
          plugin_music_limit: 50
          plugin_music_mode: top
          plugin_music_top_type: tracks
          plugin_music_time_range: long
          plugin_music_played_at: yes
          plugin_music_provider: spotify
          plugin_music_token: "${{ secrets.SPOTIFY_CLIENT_ID }}, ${{ secrets.SPOTIFY_CLIENT_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}"
